config/routes.rb
require 'sidekiq/web'

HerokuDashboard::Application.routes.draw do

  namespace :admin do
    root to: 'users#index'

    resources :users, except: :show
  end

  root to: 'dashboard#index'

  get "login" => "sessions#new", as: 'login'
  get "/auth/:provider/callback" => "sessions#create"
  match 'signout', to: 'sessions#destroy', as: 'logout', via: [:get, :post]

  mount Sidekiq::Web => '/sidekiq'

  get "dashboard/index"
  get "dynos/info" => 'app_groups#dynos_status'
  get "addons/info" => 'app_groups#addons_status'
  get "group/:tag" => 'app_groups#show', as: :group
  scope :settings do
    post "apps/multiple" => 'heroku_apps#multiple_create', as: 'multiple_create'
    put "apps/multiple" => 'heroku_apps#multiple_update', as: 'multiple_update'
    resources :apps, controller: 'heroku_apps', as: 'heroku_apps', except: [:create] do
      member do
        put :update_api
      end
    end
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @app_groups = AppGroup.all
  end
end

app/views/dashboard/index.html.haml
.row
  .offset8.pull-right
    - visible_style = AppGroup.any_async_running? ? '' : 'display: none;'
    #async-running-status.label.label-warning{:style => "#{visible_style}"} Async running...
    #async-run-btn.btn.btn-info= link_to 'Update App', multiple_update_path(format: :json), method: :put, remote: true

.row
  .span6
    #dynos-chart-holder
  .span6
    #addons-chart-holder


- @app_groups.each do |group|
  .well.row
    .span2
    .span6
      %h1.text-center
        = link_to group.name, group_path(group.name)
        = content_tag(:i, '', class: 'icon-tags')
    .span3
      - if group.apps.present?
        %h4
          = "#{group.dynos_count}"
          %small dynos
        %h4
          = "#{number_to_currency(group.addon_cost)}"
          %small Addons
  - if group.apps.present?
    - group.apps.each do |app|
      .offset2
        %h3
          = formatted_dynos_status_label(app)
          = link_to app.name, heroku_app_path(app)
          %small= link_to app.web_url, app.web_url
        %dl.dl-horizontal
          %dt dynos
          %dd= app.dynos_summary
          %dt Addon Cost
          %dd= number_to_currency(app.addon_cost)
  - else
    %p.text-center No Apps.
    %hr/

:coffee
  $(document).ready ->

    dynosChartPosition =
      positionId: 'dynos-chart-holder'
      chart_x: 300
      chart_y: 200
      radial: 120
      title_x: 280
      title_y: 30
      title_pos: "west"
    HerokuDashboard.displayChart('Dynos', 20000, "#{dynos_info_path(format: :json)}", dynosChartPosition)

    addonsChartPosition =
      positionId: 'addons-chart-holder'
      chart_x: 280
      chart_y: 200
      radial: 120
      title_x: 260
      title_y: 30
      title_pos: "west"
    HerokuDashboard.displayChart('Addons', 2500, "#{addons_info_path(format: :json)}", addonsChartPosition)

    $('body').on 'ajax:success', '#async-run-btn', (data, res, xhr) ->
      $('#async-running-status').show()