config/routes.rb
require 'sidekiq/web'

HerokuDashboard::Application.routes.draw do

  namespace :admin do
    root to: 'users#index'

    resources :users, except: :show
  end

  root to: 'dashboard#index'

  get "login" => "sessions#new", as: 'login'
  get "/auth/:provider/callback" => "sessions#create"
  match 'signout', to: 'sessions#destroy', as: 'logout', via: [:get, :post]

  mount Sidekiq::Web => '/sidekiq'

  get "dashboard/index"
  get "dynos/info" => 'app_groups#dynos_status'
  get "addons/info" => 'app_groups#addons_status'
  get "group/:tag" => 'app_groups#show', as: :group
  scope :settings do
    post "apps/multiple" => 'heroku_apps#multiple_create', as: 'multiple_create'
    put "apps/multiple" => 'heroku_apps#multiple_update', as: 'multiple_update'
    resources :apps, controller: 'heroku_apps', as: 'heroku_apps', except: [:create] do
      member do
        put :update_api
      end
    end
  end

end

app/models/heroku_app.rb
class HerokuApp < ActiveRecord::Base
  acts_as_taggable

  attr_accessor :api_updatable, :auth_token

  has_many :addons, dependent: :destroy
  accepts_nested_attributes_for :addons, allow_destroy: true
  has_many :dynos, dependent: :destroy
  accepts_nested_attributes_for :dynos, allow_destroy: true

  before_save :reset_resources
  before_validation :update_api_info, on: :create

  validates :name, presence: true, uniqueness: true  # TODO: DBでユニーク制約を入れる
  validate :validate_exist_on_heroku, on: :create

  def self.multiple_create(params, token)
    result = {success: [], failed: []}
    params.each_pair do |k, v|
      begin
        app = HerokuApp.new(name: v[:name], tag_list: v[:tags], auth_token: token)
        app.save!
        result[:success] << "'#{k}' : successfully created."
      rescue => e
        logger.warn "Faild: #{e.message}"
        result[:failed] << "'#{k}' : failed."
      end
    end
    result
  end

  def self.multiple_update
    result = {success: [], failed: []}
    HerokuApp.all.each do |app|
      begin
        app.update_attributes!(Api::App.new(app.name).attributes)
        result[:success] << app.name
      rescue
        result[:failed] << "#{app.name}: NG"
      end
    end
    result.store(:success, "Update OK, #{result[:success].size} Apps") unless result[:success].empty?
    result
  end

  # TODO: リファクタリング: dyno 周りの処理をクラス化するなどしてすっきりさせる。
  def dynos_summary
    dynos_kind_dup = dynos_kind.dup
    total = dynos_kind_dup.delete(:total)
    dynos_desc = dynos_kind_dup.to_a.map do |d|
      "#{d.first}: #{d.last.to_a.join('x ')}"
    end
    "#{total} (#{dynos_desc.join(', ')})"
  end

  def dynos_kind
    dynos_dup = dynos.dup
    uniq_keys = dynos_dup.map{|d| d.name.sub(/\..*/, '')}.sort.uniq
    hs = {}
    uniq_keys.map do |key|
      match_dynos = dynos_dup.select{|d| d.name =~ Regexp.new("#{key}.*")}
      hs[key] = {"#{match_dynos.first.size}" => match_dynos.size}
    end
    hs.merge(total: dynos_dup.map(&:size).sum)
  end

  def dynos_statuses
    dynos.pluck(:status)
  end

  def dynos_status_summary
    statuses = dynos_statuses
    if statuses.uniq.size == 1
      statuses.first
    else
      case dynos_status_score
      when -1 then 'No Dyno'
      when 0 then 'Down'
      when 1..99
        '1..99'
      when 100 then 'Up'
      else
        "..."
      end
    end
  end

  def dynos_status_score
    return -1 if dynos_statuses.empty?
    all_status = dynos_statuses.size.to_f
    ok = dynos_statuses.select{|s| s == "up"}.size.to_f
    (ok / all_status) * 100
  end

  def addon_cost
    addons.inject(0){|sum, addon| sum += addon.price_doller }
  end

  def self.all_async!(token)
    find_each do |app|
      app.auth_token = token
      app.async_get_api!
    end
  end

  def async_get_api!
    update_attributes!(async_running: true)
    HerokuInfoUpdater.perform_async(id, auth_token)
  rescue => e
    logger.warn "Failed: #{e.message}"
  end


  private

  def reset_resources
    if api_updatable
      addons.where.not(created_at: nil).delete_all
      dynos.where.not(created_at: nil).delete_all
    end
  end

  def validate_exist_on_heroku
    errors.add :base, "Don't exit on Heroku'" unless Api::App.new(name, self.auth_token).exist?
  end

  def update_api_info
    self.attributes = Api::App.new(name, self.auth_token).attributes
  end
end

app/controllers/heroku_apps_controller.rb
class HerokuAppsController < ApplicationController
  before_action :set_heroku_app, only: [:show, :edit, :update, :update_api, :destroy]

  def index
    @heroku_apps = HerokuApp.order(:name)
  end

  def show
  end

  def new
    @app_names = Api::App.app_names(current_user.access_token) - HerokuApp.pluck(:name)
  end

  def edit
  end

  def multiple_create
    result = HerokuApp.multiple_create(multiple_app_params, current_user.access_token)
    redirect_to heroku_apps_path, notice: result[:success], alert: result[:failed]
  end

  def multiple_update
    HerokuApp.all_async!(current_user.access_token)
    render json: {}, status: :ok
  end

  def update
    if @heroku_app.update(heroku_app_params)
      redirect_to @heroku_app, notice: 'Heroku app was successfully updated.'
    else
      render :edit
    end
  end

  def update_api
    @heroku_app.async_get_api!
    render json: {}, status: :ok
  rescue => e
    logger.warn "#{e.message}"
    redirect_to heroku_app_path(@heroku_app), alert: "Failed: #{e.message}"
  end

  def destroy
    @heroku_app.destroy
    redirect_to heroku_apps_url
  end


  private

  def set_heroku_app
    @heroku_app = HerokuApp.find(params[:id])
    @heroku_app.auth_token = current_user.access_token
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def heroku_app_params
    params.require(:heroku_app).permit(:name, :tag_list)
  end

  def multiple_app_params
    params[:apps].select{|k, v| v.has_key?(:name)}
  end
end

app/views/heroku_apps/_form.html.haml
= form_for @heroku_app do |f|
  - if @heroku_app.errors.any?
    #error_explanation
      %h2= "#{pluralize(@heroku_app.errors.count, "error")} prohibited this heroku_app from being saved:"
      %ul
        - @heroku_app.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :tag_list
    = f.text_field :tag_list
  .actions
    = f.submit 'Save'

app/views/heroku_apps/edit.html.haml
%h1 Editing heroku_app

= render 'form'

= link_to 'Show', @heroku_app
\|
= link_to 'Back', heroku_apps_path

app/views/heroku_apps/index.html.haml
.btn.btn-info.pull-right= link_to 'New App', new_heroku_app_path
%h1 Heroku Apps

%table.table.table-striped
  - @heroku_apps.each do |heroku_app|
    %tr
      %td= formatted_dynos_status_label(heroku_app)
      %td
        %h3
          = link_to heroku_app.name, heroku_app
          %small
            = raw linked_tags(heroku_app.tag_list)
            = content_tag(:i, '', class: 'icon-tags')
      %td= link_to content_tag(:i, '', :class => 'icon-trash'), heroku_app, :method => :delete, :data => { :confirm => 'Are you sure?' }
%hr/

app/views/heroku_apps/new.html.haml
%h1.text-center New Heroku Apps

- if @app_names.empty?
  .text-center.alert.alert-warning Not exist registration Heroku apps.
- else
  .offset2
    = form_tag multiple_create_path, class: 'form-inline' do
      - @app_names.each do |name|
        %h4
          .checkbox
            = check_box_tag "apps[#{name}][name]", name
            %strong= name
            = text_field_tag "apps[#{name}][tags]", nil, placeholder: "Tag.."
      .btn-block
        = submit_tag 'Create', class: "btn btn-primary"
        .btn.btn-default= link_to 'Cancel', heroku_apps_path

app/views/heroku_apps/show.html.haml
%p.text-right= "Released: #{@heroku_app.try(:released_at).to_s}"

%h1.text-center
  = formatted_dynos_status_label(@heroku_app)
  = @heroku_app.name
  %small
    = raw linked_tags(@heroku_app.tag_list)
    = link_to content_tag(:i, '', class: 'icon-tags'), edit_heroku_app_path(@heroku_app)
  .btn.btn-danger.pull-right= link_to content_tag(:i, '', class: 'icon-trash'), @heroku_app, method: :delete, data: { confirm: 'Are you sure?' }

%p.text-center= link_to @heroku_app.web_url, @heroku_app.web_url

.row
  .span8
    .span7.offset1
      %dl.dl-horizontal
        - @heroku_app.dynos.sort.each do |dyno|
          %dt= dyno.name
          %dd= labeling_dyno_status(dyno.status)

      .pull-right
        - visible_style = @heroku_app.async_running? ? '' : 'display: none;'
        #async-running-status.label.label-warning{:style => "#{visible_style}"} Async running...
        #async-run-btn.btn.btn-info= link_to 'Update App Info', update_api_heroku_app_path(@heroku_app, format: :json), method: :put, remote: true

      - if @heroku_app.addons.present?
        %h3
          Addons
          %small= number_to_currency(@heroku_app.addon_cost)
        - @heroku_app.addons.each do |addon|
          .well
            %strong= addon.description
            %dl.dl-horizontal
              %dt Plan
              %dd= addon.plan_description
              %dt Price(cent)
              %dd= "#{addon.price['cents']} / #{addon.price['unit']}"
              %dt Group
              %dd= addon.group_description
              %dt sso_url
              %dd= link_to(addon.sso_url, addon.sso_url) if addon.sso_url.present?
      -else
        No Addons.
  .span3.offset1
    .well.sidebar-nav
      %h4= "\"#{@heroku_app.tag_list}\" Apps"
      %ul.nav.nav-list
        - @heroku_app.find_related_tags.each do |app|
          %li= link_to app.name, heroku_app_path(app)
:coffee
  $ ->
    $('body').on 'ajax:success', '#async-run-btn', (data, res, xhr) ->
      $('#async-running-status').show()