config/routes.rb
require 'sidekiq/web'

HerokuDashboard::Application.routes.draw do

  namespace :admin do
    root to: 'users#index'

    resources :users, except: :show
  end

  root to: 'dashboard#index'

  get "login" => "sessions#new", as: 'login'
  get "/auth/:provider/callback" => "sessions#create"
  match 'signout', to: 'sessions#destroy', as: 'logout', via: [:get, :post]

  mount Sidekiq::Web => '/sidekiq'

  get "dashboard/index"
  get "dynos/info" => 'app_groups#dynos_status'
  get "addons/info" => 'app_groups#addons_status'
  get "group/:tag" => 'app_groups#show', as: :group
  scope :settings do
    post "apps/multiple" => 'heroku_apps#multiple_create', as: 'multiple_create'
    put "apps/multiple" => 'heroku_apps#multiple_update', as: 'multiple_update'
    resources :apps, controller: 'heroku_apps', as: 'heroku_apps', except: [:create] do
      member do
        put :update_api
      end
    end
  end

end

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "My Heroku Dashboard"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    / For third-generation iPad with high-resolution Retina display:
    / Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    / For iPhone with high-resolution Retina display:
    / Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    / For first- and second-generation iPad:
    / Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    / Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
  %body
    %a{href: "https://github.com/n-sakuma/heroku-dashboard", target: "blank"}
      %img{alt: "Fork me on GitHub", src: "https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png", style: "position: absolute; top: 0; right: 0; border: 0; z-index: 1050;"}/
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          .brand= link_to_if logged_in?, 'Mentough Dashboard', root_path
          .container.nav-collapse
            %ul.nav
              - if logged_in?
                %li= link_to "Apps",  heroku_apps_path
                %li= link_to "sign out",  logout_path

    .container
      .row
        .span12
          = bootstrap_flash
          = yield